// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type Client,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import type {
  AuthJwtLoginData,
  AuthJwtLoginResponses,
  AuthJwtLoginErrors,
  AuthJwtLogoutData,
  AuthJwtLogoutResponses,
  RegisterRegisterData,
  RegisterRegisterResponses,
  RegisterRegisterErrors,
  RegisterRegisterClienteData,
  RegisterRegisterClienteResponses,
  RegisterRegisterClienteErrors,
  RegisterRegisterProfesionalData,
  RegisterRegisterProfesionalResponses,
  RegisterRegisterProfesionalErrors,
  ResetForgotPasswordData,
  ResetForgotPasswordResponses,
  ResetForgotPasswordErrors,
  ResetResetPasswordData,
  ResetResetPasswordResponses,
  ResetResetPasswordErrors,
  VerifyRequestTokenData,
  VerifyRequestTokenResponses,
  VerifyRequestTokenErrors,
  VerifyVerifyData,
  VerifyVerifyResponses,
  VerifyVerifyErrors,
  UsersCurrentUserData,
  UsersCurrentUserResponses,
  UsersPatchCurrentUserData,
  UsersPatchCurrentUserResponses,
  UsersPatchCurrentUserErrors,
  UsersDeleteUserData,
  UsersDeleteUserResponses,
  UsersDeleteUserErrors,
  UsersUserData,
  UsersUserResponses,
  UsersUserErrors,
  UsersPatchUserData,
  UsersPatchUserResponses,
  UsersPatchUserErrors,
  ClientesDeleteMeData,
  ClientesDeleteMeResponses,
  ClientesReadMeData,
  ClientesReadMeResponses,
  ClientesUpdateMeData,
  ClientesUpdateMeResponses,
  ClientesUpdateMeErrors,
  ClientesDeleteData,
  ClientesDeleteResponses,
  ClientesDeleteErrors,
  ClientesReadData,
  ClientesReadResponses,
  ClientesReadErrors,
  ClientesUpdateData,
  ClientesUpdateResponses,
  ClientesUpdateErrors,
  ProfesionalesDeleteMeData,
  ProfesionalesDeleteMeResponses,
  ProfesionalesReadMeData,
  ProfesionalesReadMeResponses,
  ProfesionalesUpdateMeData,
  ProfesionalesUpdateMeResponses,
  ProfesionalesUpdateMeErrors,
  ProfesionalesDeleteData,
  ProfesionalesDeleteResponses,
  ProfesionalesDeleteErrors,
  ProfesionalesReadData,
  ProfesionalesReadResponses,
  ProfesionalesReadErrors,
  ProfesionalesUpdateData,
  ProfesionalesUpdateResponses,
  ProfesionalesUpdateErrors,
  ReadItemData,
  ReadItemResponses,
  ReadItemErrors,
  CreateItemData,
  CreateItemResponses,
  CreateItemErrors,
  DeleteItemData,
  DeleteItemResponses,
  DeleteItemErrors,
} from "./types.gen";
import { client } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Login → JWT
 * Login and return a JWT.
 *
 * Create the user with POST /auth/register first. Optional:
 * POST /auth/request-verify-token then POST /auth/verify.
 */
export const authJwtLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthJwtLoginData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AuthJwtLoginResponses,
    AuthJwtLoginErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: "json",
    url: "/api/v1/auth/jwt/login",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });
};

/**
 * Logout
 * Invalidate the current JWT.
 *
 * Call after POST /auth/jwt/login when the user signs out.
 */
export const authJwtLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthJwtLogoutData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthJwtLogoutResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/jwt/logout",
    ...options,
  });
};

/**
 * Create user
 * Create user.
 *
 * Next: POST /auth/request-verify-token, POST /auth/verify, then
 * POST /auth/jwt/login.
 */
export const registerRegister = <ThrowOnError extends boolean = false>(
  options: Options<RegisterRegisterData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RegisterRegisterResponses,
    RegisterRegisterErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Register as cliente
 * Create a usuario and its cliente profile in one request.
 *
 * Combines POST /auth/register + POST /users/me/cliente. Next:
 * POST /auth/request-verify-token, POST /auth/verify, then
 * POST /auth/jwt/login.
 */
export const registerRegisterCliente = <ThrowOnError extends boolean = false>(
  options: Options<RegisterRegisterClienteData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RegisterRegisterClienteResponses,
    RegisterRegisterClienteErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/auth/register/cliente",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Register as profesional
 * Create a usuario and its profesional profile in one request.
 *
 * Combines POST /auth/register + POST /users/me/profesional. Starts as
 * estado_verificacion=pendiente; verification review happens out of band.
 * Next: POST /auth/request-verify-token, POST /auth/verify, then
 * POST /auth/jwt/login.
 */
export const registerRegisterProfesional = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RegisterRegisterProfesionalData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RegisterRegisterProfesionalResponses,
    RegisterRegisterProfesionalErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/auth/register/profesional",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Start reset (sends email)
 * Start reset and send email.
 *
 * Complete with POST /auth/reset-password, then sign in with
 * POST /auth/jwt/login.
 */
export const resetForgotPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetForgotPasswordData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ResetForgotPasswordResponses,
    ResetForgotPasswordErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/auth/forgot-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Complete reset with token
 * Complete reset with the emailed token.
 *
 * Start with POST /auth/forgot-password, then POST /auth/jwt/login.
 */
export const resetResetPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetResetPasswordData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ResetResetPasswordResponses,
    ResetResetPasswordErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/auth/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Request verification email
 * Request verification email.
 *
 * Then POST /auth/verify, then POST /auth/jwt/login.
 */
export const verifyRequestToken = <ThrowOnError extends boolean = false>(
  options: Options<VerifyRequestTokenData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    VerifyRequestTokenResponses,
    VerifyRequestTokenErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/auth/request-verify-token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Verify email with token
 * Verify email with token.
 *
 * Request it with POST /auth/request-verify-token, then
 * POST /auth/jwt/login.
 */
export const verifyVerify = <ThrowOnError extends boolean = false>(
  options: Options<VerifyVerifyData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    VerifyVerifyResponses,
    VerifyVerifyErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/auth/verify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Current authenticated user
 * Return the current authenticated user.
 *
 * Requires POST /auth/jwt/login.
 */
export const usersCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<UsersCurrentUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersCurrentUserResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/me",
    ...options,
  });
};

/**
 * Update current user
 * Update the current authenticated user.
 *
 * Requires POST /auth/jwt/login. Superusers can PATCH /users/{id}
 * instead.
 */
export const usersPatchCurrentUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersPatchCurrentUserData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UsersPatchCurrentUserResponses,
    UsersPatchCurrentUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete user by id (superuser)
 * Delete user by id.
 *
 * Superuser only after POST /auth/jwt/login. This also removes that
 * user's items.
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersDeleteUserData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    UsersDeleteUserResponses,
    UsersDeleteUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/{id}",
    ...options,
  });
};

/**
 * Get user by id (superuser)
 * Get user by id.
 *
 * Superuser only after POST /auth/jwt/login. Use GET /users/me for
 * the current user.
 */
export const usersUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUserData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    UsersUserResponses,
    UsersUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/{id}",
    ...options,
  });
};

/**
 * Update user by id (superuser)
 * Update user by id.
 *
 * Superuser only after POST /auth/jwt/login. Use PATCH /users/me for
 * the current user.
 */
export const usersPatchUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersPatchUserData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UsersPatchUserResponses,
    UsersPatchUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete current user's cliente profile
 * Delete the current user's cliente profile.
 *
 * Requires POST /auth/jwt/login.
 */
export const clientesDeleteMe = <ThrowOnError extends boolean = false>(
  options?: Options<ClientesDeleteMeData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    ClientesDeleteMeResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/me/cliente",
    ...options,
  });
};

/**
 * Get current user's cliente profile
 * Get the current user's cliente profile.
 *
 * Requires POST /auth/jwt/login.
 */
export const clientesReadMe = <ThrowOnError extends boolean = false>(
  options?: Options<ClientesReadMeData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ClientesReadMeResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/me/cliente",
    ...options,
  });
};

/**
 * Update current user's cliente profile
 * Update the current user's cliente profile.
 *
 * Requires POST /auth/jwt/login.
 */
export const clientesUpdateMe = <ThrowOnError extends boolean = false>(
  options: Options<ClientesUpdateMeData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    ClientesUpdateMeResponses,
    ClientesUpdateMeErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/me/cliente",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete cliente profile by user id (superuser)
 * Delete a cliente profile by user id.
 *
 * Superuser only after POST /auth/jwt/login.
 */
export const clientesDelete = <ThrowOnError extends boolean = false>(
  options: Options<ClientesDeleteData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    ClientesDeleteResponses,
    ClientesDeleteErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/{id}/cliente",
    ...options,
  });
};

/**
 * Get cliente profile by user id (superuser)
 * Get a cliente profile by user id.
 *
 * Superuser only after POST /auth/jwt/login. Use GET /users/me/cliente
 * for the current user.
 */
export const clientesRead = <ThrowOnError extends boolean = false>(
  options: Options<ClientesReadData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ClientesReadResponses,
    ClientesReadErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/{id}/cliente",
    ...options,
  });
};

/**
 * Update cliente profile by user id (superuser)
 * Update a cliente profile by user id.
 *
 * Superuser only after POST /auth/jwt/login. Use PATCH /users/me/cliente
 * for the current user.
 */
export const clientesUpdate = <ThrowOnError extends boolean = false>(
  options: Options<ClientesUpdateData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    ClientesUpdateResponses,
    ClientesUpdateErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/{id}/cliente",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete current user's profesional profile
 * Delete the current user's profesional profile.
 *
 * Requires POST /auth/jwt/login.
 */
export const profesionalesDeleteMe = <ThrowOnError extends boolean = false>(
  options?: Options<ProfesionalesDeleteMeData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    ProfesionalesDeleteMeResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/me/profesional",
    ...options,
  });
};

/**
 * Get current user's profesional profile
 * Get the current user's profesional profile.
 *
 * Requires POST /auth/jwt/login.
 */
export const profesionalesReadMe = <ThrowOnError extends boolean = false>(
  options?: Options<ProfesionalesReadMeData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ProfesionalesReadMeResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/me/profesional",
    ...options,
  });
};

/**
 * Update current user's profesional profile
 * Update the current user's profesional profile.
 *
 * Requires POST /auth/jwt/login. Only self-editable fields
 * (anos_experiencia, foto_perfil_url) - verification/contract fields are
 * superuser-only via PATCH /users/{id}/profesional.
 */
export const profesionalesUpdateMe = <ThrowOnError extends boolean = false>(
  options: Options<ProfesionalesUpdateMeData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    ProfesionalesUpdateMeResponses,
    ProfesionalesUpdateMeErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/me/profesional",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete profesional profile by user id (superuser)
 * Delete a profesional profile by user id.
 *
 * Superuser only after POST /auth/jwt/login.
 */
export const profesionalesDelete = <ThrowOnError extends boolean = false>(
  options: Options<ProfesionalesDeleteData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    ProfesionalesDeleteResponses,
    ProfesionalesDeleteErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/{id}/profesional",
    ...options,
  });
};

/**
 * Get profesional profile by user id (superuser)
 * Get a profesional profile by user id.
 *
 * Superuser only after POST /auth/jwt/login. Use GET
 * /users/me/profesional for the current user.
 */
export const profesionalesRead = <ThrowOnError extends boolean = false>(
  options: Options<ProfesionalesReadData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ProfesionalesReadResponses,
    ProfesionalesReadErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/{id}/profesional",
    ...options,
  });
};

/**
 * Update profesional profile by user id (superuser)
 * Update a profesional profile by user id, including verification and
 * contract fields.
 *
 * Superuser only after POST /auth/jwt/login. Use PATCH
 * /users/me/profesional for self-editable fields only.
 */
export const profesionalesUpdate = <ThrowOnError extends boolean = false>(
  options: Options<ProfesionalesUpdateData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    ProfesionalesUpdateResponses,
    ProfesionalesUpdateErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/{id}/profesional",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Paginated list (authenticated)
 * Return a paginated list of the current user's items.
 *
 * Requires POST /auth/jwt/login.
 */
export const readItem = <ThrowOnError extends boolean = false>(
  options?: Options<ReadItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadItemResponses,
    ReadItemErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/items/",
    ...options,
  });
};

/**
 * Create item for current user
 * Create an item for the current user.
 *
 * Requires POST /auth/jwt/login.
 */
export const createItem = <ThrowOnError extends boolean = false>(
  options: Options<CreateItemData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateItemResponses,
    CreateItemErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/items/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete own item
 * Delete the current user's item by id.
 *
 * Requires POST /auth/jwt/login. Returns 404 if missing or not owned.
 */
export const deleteItem = <ThrowOnError extends boolean = false>(
  options: Options<DeleteItemData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteItemResponses,
    DeleteItemErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/items/{item_id}",
    ...options,
  });
};
