// This file is auto-generated by @hey-api/openapi-ts

/**
 * Body_auth-reset:forgot_password
 */
export type BodyAuthResetForgotPassword = {
  /**
   * Email
   */
  email: string;
};

/**
 * Body_auth-reset:reset_password
 */
export type BodyAuthResetResetPassword = {
  /**
   * Token
   */
  token: string;
  /**
   * Password
   */
  password: string;
};

/**
 * Body_auth-verify:request-token
 */
export type BodyAuthVerifyRequestToken = {
  /**
   * Email
   */
  email: string;
};

/**
 * Body_auth-verify:verify
 */
export type BodyAuthVerifyVerify = {
  /**
   * Token
   */
  token: string;
};

/**
 * ClienteAdminUpdate
 */
export type ClienteAdminUpdate = {
  /**
   * Direccion Default
   */
  direccion_default?: string | null;
  /**
   * Repeat Customer
   */
  repeat_customer?: boolean | null;
};

/**
 * ClienteRead
 */
export type ClienteRead = {
  /**
   * Direccion Default
   */
  direccion_default?: string | null;
  /**
   * Referido Por Id
   */
  referido_por_id?: string | null;
  /**
   * Usuario Id
   */
  usuario_id: string;
  /**
   * Repeat Customer
   */
  repeat_customer: boolean;
  /**
   * Creado En
   */
  creado_en: string;
  /**
   * Actualizado En
   */
  actualizado_en: string;
};

/**
 * ClienteRegisterCreate
 */
export type ClienteRegisterCreate = {
  /**
   * Direccion Default
   */
  direccion_default?: string | null;
  /**
   * Referido Por Id
   */
  referido_por_id?: string | null;
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
  /**
   * Nombre Completo
   */
  nombre_completo: string;
  /**
   * Whatsapp
   */
  whatsapp?: string | null;
};

/**
 * ClienteUpdate
 */
export type ClienteUpdate = {
  /**
   * Direccion Default
   */
  direccion_default?: string | null;
};

/**
 * EstadoVerificacionProfesional
 */
export type EstadoVerificacionProfesional =
  | "pendiente"
  | "verificado"
  | "revisar_manual"
  | "rechazado";

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Quantity
   */
  quantity?: number | null;
};

/**
 * ItemRead
 */
export type ItemRead = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Quantity
   */
  quantity?: number | null;
  /**
   * Id
   */
  id: string;
  /**
   * User Id
   */
  user_id: string;
};

/**
 * Page[ItemRead]
 */
export type PageItemRead = {
  /**
   * Items
   */
  items: Array<ItemRead>;
  /**
   * Total
   */
  total?: number | null;
  /**
   * Page
   */
  page: number | null;
  /**
   * Size
   */
  size: number | null;
  /**
   * Pages
   */
  pages?: number | null;
};

/**
 * ProfesionalAdminUpdate
 */
export type ProfesionalAdminUpdate = {
  /**
   * Anos Experiencia
   */
  anos_experiencia?: number | null;
  /**
   * Foto Perfil Url
   */
  foto_perfil_url?: string | null;
  estado_verificacion?: EstadoVerificacionProfesional | null;
  /**
   * Score Calificacion
   */
  score_calificacion?: number | null;
  /**
   * Whatsapp Verificado
   */
  whatsapp_verificado?: boolean | null;
  /**
   * Contrato Aceptado
   */
  contrato_aceptado?: boolean | null;
  /**
   * Trabajos Gratis Restantes
   */
  trabajos_gratis_restantes?: number | null;
};

/**
 * ProfesionalRead
 */
export type ProfesionalRead = {
  documento_tipo: TipoDocumento;
  /**
   * Documento Numero
   */
  documento_numero: string;
  /**
   * Anos Experiencia
   */
  anos_experiencia?: number | null;
  /**
   * Foto Perfil Url
   */
  foto_perfil_url?: string | null;
  /**
   * Usuario Id
   */
  usuario_id: string;
  estado_verificacion: EstadoVerificacionProfesional;
  /**
   * Score Calificacion
   */
  score_calificacion?: number | null;
  /**
   * Whatsapp Verificado
   */
  whatsapp_verificado: boolean;
  /**
   * Contrato Aceptado
   */
  contrato_aceptado: boolean;
  /**
   * Contrato Aceptado En
   */
  contrato_aceptado_en?: string | null;
  /**
   * Trabajos Gratis Restantes
   */
  trabajos_gratis_restantes: number;
  /**
   * Creado En
   */
  creado_en: string;
  /**
   * Actualizado En
   */
  actualizado_en: string;
};

/**
 * ProfesionalRegisterCreate
 */
export type ProfesionalRegisterCreate = {
  documento_tipo: TipoDocumento;
  /**
   * Documento Numero
   */
  documento_numero: string;
  /**
   * Anos Experiencia
   */
  anos_experiencia?: number | null;
  /**
   * Foto Perfil Url
   */
  foto_perfil_url?: string | null;
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
  /**
   * Nombre Completo
   */
  nombre_completo: string;
  /**
   * Whatsapp
   */
  whatsapp?: string | null;
};

/**
 * ProfesionalUpdate
 */
export type ProfesionalUpdate = {
  /**
   * Anos Experiencia
   */
  anos_experiencia?: number | null;
  /**
   * Foto Perfil Url
   */
  foto_perfil_url?: string | null;
};

/**
 * TipoDocumento
 * Each member carries a human-readable Spanish label alongside its code
 * (e.g. TipoDocumento.CC.label == "Cédula de Ciudadanía"), used to render
 * admin dropdown options — the codes alone aren't self-explanatory.
 */
export type TipoDocumento =
  | "CC"
  | "CE"
  | "TI"
  | "RC"
  | "PA"
  | "MS"
  | "PE"
  | "CN"
  | "PT"
  | "SC";

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
  /**
   * Nombre Completo
   */
  nombre_completo: string;
  /**
   * Whatsapp
   */
  whatsapp?: string | null;
};

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Email
   */
  email: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Is Superuser
   */
  is_superuser?: boolean;
  /**
   * Is Verified
   */
  is_verified?: boolean;
  /**
   * Nombre Completo
   */
  nombre_completo: string;
  /**
   * Whatsapp
   */
  whatsapp?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Password
   */
  password?: string | null;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
  /**
   * Nombre Completo
   */
  nombre_completo?: string | null;
  /**
   * Whatsapp
   */
  whatsapp?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * Body_auth-auth:jwt.login
 */
export type Login = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

export type AuthJwtLoginData = {
  body: Login;
  path?: never;
  query?: never;
  url: "/api/v1/auth/jwt/login";
};

export type AuthJwtLoginErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthJwtLoginError = AuthJwtLoginErrors[keyof AuthJwtLoginErrors];

export type AuthJwtLoginResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthJwtLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/jwt/logout";
};

export type AuthJwtLogoutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RegisterRegisterData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/api/v1/auth/register";
};

export type RegisterRegisterErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterRegisterError =
  RegisterRegisterErrors[keyof RegisterRegisterErrors];

export type RegisterRegisterResponses = {
  /**
   * Successful Response
   */
  201: UserRead;
};

export type RegisterRegisterResponse =
  RegisterRegisterResponses[keyof RegisterRegisterResponses];

export type RegisterRegisterClienteData = {
  body: ClienteRegisterCreate;
  path?: never;
  query?: never;
  url: "/api/v1/auth/register/cliente";
};

export type RegisterRegisterClienteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterRegisterClienteError =
  RegisterRegisterClienteErrors[keyof RegisterRegisterClienteErrors];

export type RegisterRegisterClienteResponses = {
  /**
   * Successful Response
   */
  201: UserRead;
};

export type RegisterRegisterClienteResponse =
  RegisterRegisterClienteResponses[keyof RegisterRegisterClienteResponses];

export type RegisterRegisterProfesionalData = {
  body: ProfesionalRegisterCreate;
  path?: never;
  query?: never;
  url: "/api/v1/auth/register/profesional";
};

export type RegisterRegisterProfesionalErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterRegisterProfesionalError =
  RegisterRegisterProfesionalErrors[keyof RegisterRegisterProfesionalErrors];

export type RegisterRegisterProfesionalResponses = {
  /**
   * Successful Response
   */
  201: UserRead;
};

export type RegisterRegisterProfesionalResponse =
  RegisterRegisterProfesionalResponses[keyof RegisterRegisterProfesionalResponses];

export type ResetForgotPasswordData = {
  body: BodyAuthResetForgotPassword;
  path?: never;
  query?: never;
  url: "/api/v1/auth/forgot-password";
};

export type ResetForgotPasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetForgotPasswordError =
  ResetForgotPasswordErrors[keyof ResetForgotPasswordErrors];

export type ResetForgotPasswordResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type ResetResetPasswordData = {
  body: BodyAuthResetResetPassword;
  path?: never;
  query?: never;
  url: "/api/v1/auth/reset-password";
};

export type ResetResetPasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetResetPasswordError =
  ResetResetPasswordErrors[keyof ResetResetPasswordErrors];

export type ResetResetPasswordResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type VerifyRequestTokenData = {
  body: BodyAuthVerifyRequestToken;
  path?: never;
  query?: never;
  url: "/api/v1/auth/request-verify-token";
};

export type VerifyRequestTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyRequestTokenError =
  VerifyRequestTokenErrors[keyof VerifyRequestTokenErrors];

export type VerifyRequestTokenResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type VerifyVerifyData = {
  body: BodyAuthVerifyVerify;
  path?: never;
  query?: never;
  url: "/api/v1/auth/verify";
};

export type VerifyVerifyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyVerifyError = VerifyVerifyErrors[keyof VerifyVerifyErrors];

export type VerifyVerifyResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type VerifyVerifyResponse =
  VerifyVerifyResponses[keyof VerifyVerifyResponses];

export type UsersCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/users/me";
};

export type UsersCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersCurrentUserResponse =
  UsersCurrentUserResponses[keyof UsersCurrentUserResponses];

export type UsersPatchCurrentUserData = {
  body: UserUpdate;
  path?: never;
  query?: never;
  url: "/api/v1/users/me";
};

export type UsersPatchCurrentUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersPatchCurrentUserError =
  UsersPatchCurrentUserErrors[keyof UsersPatchCurrentUserErrors];

export type UsersPatchCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersPatchCurrentUserResponse =
  UsersPatchCurrentUserResponses[keyof UsersPatchCurrentUserResponses];

export type UsersDeleteUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/users/{id}";
};

export type UsersDeleteUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersDeleteUserError =
  UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type UsersDeleteUserResponse =
  UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/users/{id}";
};

export type UsersUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersUserError = UsersUserErrors[keyof UsersUserErrors];

export type UsersUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersUserResponse = UsersUserResponses[keyof UsersUserResponses];

export type UsersPatchUserData = {
  body: UserUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/users/{id}";
};

export type UsersPatchUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersPatchUserError =
  UsersPatchUserErrors[keyof UsersPatchUserErrors];

export type UsersPatchUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersPatchUserResponse =
  UsersPatchUserResponses[keyof UsersPatchUserResponses];

export type ClientesDeleteMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/users/me/cliente";
};

export type ClientesDeleteMeResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type ClientesDeleteMeResponse =
  ClientesDeleteMeResponses[keyof ClientesDeleteMeResponses];

export type ClientesReadMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/users/me/cliente";
};

export type ClientesReadMeResponses = {
  /**
   * Successful Response
   */
  200: ClienteRead;
};

export type ClientesReadMeResponse =
  ClientesReadMeResponses[keyof ClientesReadMeResponses];

export type ClientesUpdateMeData = {
  body: ClienteUpdate;
  path?: never;
  query?: never;
  url: "/api/v1/users/me/cliente";
};

export type ClientesUpdateMeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ClientesUpdateMeError =
  ClientesUpdateMeErrors[keyof ClientesUpdateMeErrors];

export type ClientesUpdateMeResponses = {
  /**
   * Successful Response
   */
  200: ClienteRead;
};

export type ClientesUpdateMeResponse =
  ClientesUpdateMeResponses[keyof ClientesUpdateMeResponses];

export type ClientesDeleteData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/users/{id}/cliente";
};

export type ClientesDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ClientesDeleteError =
  ClientesDeleteErrors[keyof ClientesDeleteErrors];

export type ClientesDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type ClientesDeleteResponse =
  ClientesDeleteResponses[keyof ClientesDeleteResponses];

export type ClientesReadData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/users/{id}/cliente";
};

export type ClientesReadErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ClientesReadError = ClientesReadErrors[keyof ClientesReadErrors];

export type ClientesReadResponses = {
  /**
   * Successful Response
   */
  200: ClienteRead;
};

export type ClientesReadResponse =
  ClientesReadResponses[keyof ClientesReadResponses];

export type ClientesUpdateData = {
  body: ClienteAdminUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/users/{id}/cliente";
};

export type ClientesUpdateErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ClientesUpdateError =
  ClientesUpdateErrors[keyof ClientesUpdateErrors];

export type ClientesUpdateResponses = {
  /**
   * Successful Response
   */
  200: ClienteRead;
};

export type ClientesUpdateResponse =
  ClientesUpdateResponses[keyof ClientesUpdateResponses];

export type ProfesionalesDeleteMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/users/me/profesional";
};

export type ProfesionalesDeleteMeResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type ProfesionalesDeleteMeResponse =
  ProfesionalesDeleteMeResponses[keyof ProfesionalesDeleteMeResponses];

export type ProfesionalesReadMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/users/me/profesional";
};

export type ProfesionalesReadMeResponses = {
  /**
   * Successful Response
   */
  200: ProfesionalRead;
};

export type ProfesionalesReadMeResponse =
  ProfesionalesReadMeResponses[keyof ProfesionalesReadMeResponses];

export type ProfesionalesUpdateMeData = {
  body: ProfesionalUpdate;
  path?: never;
  query?: never;
  url: "/api/v1/users/me/profesional";
};

export type ProfesionalesUpdateMeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProfesionalesUpdateMeError =
  ProfesionalesUpdateMeErrors[keyof ProfesionalesUpdateMeErrors];

export type ProfesionalesUpdateMeResponses = {
  /**
   * Successful Response
   */
  200: ProfesionalRead;
};

export type ProfesionalesUpdateMeResponse =
  ProfesionalesUpdateMeResponses[keyof ProfesionalesUpdateMeResponses];

export type ProfesionalesDeleteData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/users/{id}/profesional";
};

export type ProfesionalesDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProfesionalesDeleteError =
  ProfesionalesDeleteErrors[keyof ProfesionalesDeleteErrors];

export type ProfesionalesDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type ProfesionalesDeleteResponse =
  ProfesionalesDeleteResponses[keyof ProfesionalesDeleteResponses];

export type ProfesionalesReadData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/users/{id}/profesional";
};

export type ProfesionalesReadErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProfesionalesReadError =
  ProfesionalesReadErrors[keyof ProfesionalesReadErrors];

export type ProfesionalesReadResponses = {
  /**
   * Successful Response
   */
  200: ProfesionalRead;
};

export type ProfesionalesReadResponse =
  ProfesionalesReadResponses[keyof ProfesionalesReadResponses];

export type ProfesionalesUpdateData = {
  body: ProfesionalAdminUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/users/{id}/profesional";
};

export type ProfesionalesUpdateErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProfesionalesUpdateError =
  ProfesionalesUpdateErrors[keyof ProfesionalesUpdateErrors];

export type ProfesionalesUpdateResponses = {
  /**
   * Successful Response
   */
  200: ProfesionalRead;
};

export type ProfesionalesUpdateResponse =
  ProfesionalesUpdateResponses[keyof ProfesionalesUpdateResponses];

export type ReadItemData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     * Page number
     */
    page?: number;
    /**
     * Size
     * Page size
     */
    size?: number;
  };
  url: "/api/v1/items/";
};

export type ReadItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadItemError = ReadItemErrors[keyof ReadItemErrors];

export type ReadItemResponses = {
  /**
   * Successful Response
   */
  200: PageItemRead;
};

export type ReadItemResponse = ReadItemResponses[keyof ReadItemResponses];

export type CreateItemData = {
  body: ItemCreate;
  path?: never;
  query?: never;
  url: "/api/v1/items/";
};

export type CreateItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateItemError = CreateItemErrors[keyof CreateItemErrors];

export type CreateItemResponses = {
  /**
   * Successful Response
   */
  200: ItemRead;
};

export type CreateItemResponse = CreateItemResponses[keyof CreateItemResponses];

export type DeleteItemData = {
  body?: never;
  path: {
    /**
     * Item Id
     */
    item_id: string;
  };
  query?: never;
  url: "/api/v1/items/{item_id}";
};

export type DeleteItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteItemError = DeleteItemErrors[keyof DeleteItemErrors];

export type DeleteItemResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ClientOptions = {
  baseURL: `${string}://openapi.json` | (string & {});
};
