// This file is auto-generated by @hey-api/openapi-ts

/**
 * Body_auth-reset:forgot_password
 */
export type BodyAuthResetForgotPassword = {
  /**
   * Email
   */
  email: string;
};

/**
 * Body_auth-reset:reset_password
 */
export type BodyAuthResetResetPassword = {
  /**
   * Token
   */
  token: string;
  /**
   * Password
   */
  password: string;
};

/**
 * Body_auth-verify:request-token
 */
export type BodyAuthVerifyRequestToken = {
  /**
   * Email
   */
  email: string;
};

/**
 * Body_auth-verify:verify
 */
export type BodyAuthVerifyVerify = {
  /**
   * Token
   */
  token: string;
};

/**
 * ClienteAdminUpdate
 */
export type ClienteAdminUpdate = {
  /**
   * Direccion Default
   */
  direccion_default?: string | null;
  /**
   * Repeat Customer
   */
  repeat_customer?: boolean | null;
};

/**
 * ClienteRead
 */
export type ClienteRead = {
  /**
   * Direccion Default
   */
  direccion_default?: string | null;
  /**
   * Referido Por Id
   */
  referido_por_id?: string | null;
  /**
   * Usuario Id
   */
  usuario_id: string;
  /**
   * Repeat Customer
   */
  repeat_customer: boolean;
  /**
   * Creado En
   */
  creado_en: string;
  /**
   * Actualizado En
   */
  actualizado_en: string;
};

/**
 * ClienteRegisterOtpCreate
 * Payload for passwordless cliente registration — no password; email
 * ownership is proven by a short-lived registration_token from
 * /auth/otp/verify instead.
 */
export type ClienteRegisterOtpCreate = {
  /**
   * Direccion Default
   */
  direccion_default?: string | null;
  /**
   * Referido Por Id
   */
  referido_por_id?: string | null;
  /**
   * Registration Token
   */
  registration_token: string;
  /**
   * Nombre Completo
   */
  nombre_completo: string;
  /**
   * Whatsapp
   */
  whatsapp?: string | null;
};

/**
 * ClienteUpdate
 */
export type ClienteUpdate = {
  /**
   * Direccion Default
   */
  direccion_default?: string | null;
};

/**
 * EstadoVerificacionProfesional
 */
export type EstadoVerificacionProfesional =
  | "pendiente"
  | "verificado"
  | "revisar_manual"
  | "rechazado";

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Quantity
   */
  quantity?: number | null;
};

/**
 * ItemRead
 */
export type ItemRead = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Quantity
   */
  quantity?: number | null;
  /**
   * Id
   */
  id: string;
  /**
   * User Id
   */
  user_id: string;
};

/**
 * OtpRequestIn
 */
export type OtpRequestIn = {
  /**
   * Email
   */
  email: string;
};

/**
 * OtpVerifyIn
 */
export type OtpVerifyIn = {
  /**
   * Email
   */
  email: string;
  /**
   * Code
   */
  code: string;
};

/**
 * Page[ItemRead]
 */
export type PageItemRead = {
  /**
   * Items
   */
  items: Array<ItemRead>;
  /**
   * Total
   */
  total?: number | null;
  /**
   * Page
   */
  page: number | null;
  /**
   * Size
   */
  size: number | null;
  /**
   * Pages
   */
  pages?: number | null;
};

/**
 * ProfesionalAdminUpdate
 */
export type ProfesionalAdminUpdate = {
  /**
   * Anos Experiencia
   */
  anos_experiencia?: number | null;
  /**
   * Foto Perfil Url
   */
  foto_perfil_url?: string | null;
  estado_verificacion?: EstadoVerificacionProfesional | null;
  /**
   * Score Calificacion
   */
  score_calificacion?: number | null;
  /**
   * Whatsapp Verificado
   */
  whatsapp_verificado?: boolean | null;
  /**
   * Contrato Aceptado
   */
  contrato_aceptado?: boolean | null;
  /**
   * Trabajos Gratis Restantes
   */
  trabajos_gratis_restantes?: number | null;
};

/**
 * ProfesionalRead
 */
export type ProfesionalRead = {
  documento_tipo: TipoDocumento;
  /**
   * Documento Numero
   */
  documento_numero: string;
  /**
   * Anos Experiencia
   */
  anos_experiencia?: number | null;
  /**
   * Foto Perfil Url
   */
  foto_perfil_url?: string | null;
  /**
   * Usuario Id
   */
  usuario_id: string;
  estado_verificacion: EstadoVerificacionProfesional;
  /**
   * Score Calificacion
   */
  score_calificacion?: number | null;
  /**
   * Whatsapp Verificado
   */
  whatsapp_verificado: boolean;
  /**
   * Contrato Aceptado
   */
  contrato_aceptado: boolean;
  /**
   * Contrato Aceptado En
   */
  contrato_aceptado_en?: string | null;
  /**
   * Trabajos Gratis Restantes
   */
  trabajos_gratis_restantes: number;
  /**
   * Creado En
   */
  creado_en: string;
  /**
   * Actualizado En
   */
  actualizado_en: string;
};

/**
 * ProfesionalRegisterOtpCreate
 * Payload for passwordless profesional registration. See
 * ClienteRegisterOtpCreate for the general pattern.
 */
export type ProfesionalRegisterOtpCreate = {
  documento_tipo: TipoDocumento;
  /**
   * Documento Numero
   */
  documento_numero: string;
  /**
   * Anos Experiencia
   */
  anos_experiencia?: number | null;
  /**
   * Foto Perfil Url
   */
  foto_perfil_url?: string | null;
  /**
   * Registration Token
   */
  registration_token: string;
  /**
   * Nombre Completo
   */
  nombre_completo: string;
  /**
   * Whatsapp
   */
  whatsapp?: string | null;
};

/**
 * ProfesionalUpdate
 */
export type ProfesionalUpdate = {
  /**
   * Anos Experiencia
   */
  anos_experiencia?: number | null;
  /**
   * Foto Perfil Url
   */
  foto_perfil_url?: string | null;
};

/**
 * TipoDocumento
 * Each member carries a human-readable Spanish label alongside its code
 * (e.g. TipoDocumento.CC.label == "Cédula de Ciudadanía"), used to render
 * admin dropdown options — the codes alone aren't self-explanatory.
 */
export type TipoDocumento = "CC" | "CE" | "PA" | "PE" | "PT";

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Email
   */
  email: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Is Superuser
   */
  is_superuser?: boolean;
  /**
   * Is Verified
   */
  is_verified?: boolean;
  /**
   * Nombre Completo
   */
  nombre_completo: string;
  /**
   * Whatsapp
   */
  whatsapp?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Password
   */
  password?: string | null;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
  /**
   * Nombre Completo
   */
  nombre_completo?: string | null;
  /**
   * Whatsapp
   */
  whatsapp?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * Body_auth-auth:google.session
 */
export type Session = {
  /**
   * Google Session Token
   */
  google_session_token: string;
};

export type AuthJwtLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/jwt/logout";
};

export type AuthJwtLogoutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthOtpRequestData = {
  body: OtpRequestIn;
  path?: never;
  query?: never;
  url: "/api/v1/auth/otp/request";
};

export type AuthOtpRequestErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthOtpRequestError =
  AuthOtpRequestErrors[keyof AuthOtpRequestErrors];

export type AuthOtpRequestResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type AuthOtpVerifyData = {
  body: OtpVerifyIn;
  path?: never;
  query?: never;
  url: "/api/v1/auth/otp/verify";
};

export type AuthOtpVerifyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthOtpVerifyError = AuthOtpVerifyErrors[keyof AuthOtpVerifyErrors];

export type AuthOtpVerifyResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthGoogleAuthorizeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/google/authorize";
};

export type AuthGoogleAuthorizeResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthGoogleCallbackData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Code
     */
    code?: string | null;
    /**
     * State
     */
    state?: string | null;
    /**
     * Error
     */
    error?: string | null;
  };
  url: "/api/v1/auth/google/callback";
};

export type AuthGoogleCallbackErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthGoogleCallbackError =
  AuthGoogleCallbackErrors[keyof AuthGoogleCallbackErrors];

export type AuthGoogleCallbackResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthGoogleSessionData = {
  body: Session;
  path?: never;
  query?: never;
  url: "/api/v1/auth/google/session";
};

export type AuthGoogleSessionErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthGoogleSessionError =
  AuthGoogleSessionErrors[keyof AuthGoogleSessionErrors];

export type AuthGoogleSessionResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthJwtRefreshData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/jwt/refresh";
};

export type AuthJwtRefreshResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RegisterRegisterClienteOtpData = {
  body: ClienteRegisterOtpCreate;
  path?: never;
  query?: never;
  url: "/api/v1/auth/register/cliente/otp";
};

export type RegisterRegisterClienteOtpErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterRegisterClienteOtpError =
  RegisterRegisterClienteOtpErrors[keyof RegisterRegisterClienteOtpErrors];

export type RegisterRegisterClienteOtpResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RegisterRegisterProfesionalOtpData = {
  body: ProfesionalRegisterOtpCreate;
  path?: never;
  query?: never;
  url: "/api/v1/auth/register/profesional/otp";
};

export type RegisterRegisterProfesionalOtpErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterRegisterProfesionalOtpError =
  RegisterRegisterProfesionalOtpErrors[keyof RegisterRegisterProfesionalOtpErrors];

export type RegisterRegisterProfesionalOtpResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ResetForgotPasswordData = {
  body: BodyAuthResetForgotPassword;
  path?: never;
  query?: never;
  url: "/api/v1/auth/forgot-password";
};

export type ResetForgotPasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetForgotPasswordError =
  ResetForgotPasswordErrors[keyof ResetForgotPasswordErrors];

export type ResetForgotPasswordResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type ResetResetPasswordData = {
  body: BodyAuthResetResetPassword;
  path?: never;
  query?: never;
  url: "/api/v1/auth/reset-password";
};

export type ResetResetPasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetResetPasswordError =
  ResetResetPasswordErrors[keyof ResetResetPasswordErrors];

export type ResetResetPasswordResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type VerifyRequestTokenData = {
  body: BodyAuthVerifyRequestToken;
  path?: never;
  query?: never;
  url: "/api/v1/auth/request-verify-token";
};

export type VerifyRequestTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyRequestTokenError =
  VerifyRequestTokenErrors[keyof VerifyRequestTokenErrors];

export type VerifyRequestTokenResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type VerifyVerifyData = {
  body: BodyAuthVerifyVerify;
  path?: never;
  query?: never;
  url: "/api/v1/auth/verify";
};

export type VerifyVerifyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyVerifyError = VerifyVerifyErrors[keyof VerifyVerifyErrors];

export type VerifyVerifyResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type VerifyVerifyResponse =
  VerifyVerifyResponses[keyof VerifyVerifyResponses];

export type UsersCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/users/me";
};

export type UsersCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersCurrentUserResponse =
  UsersCurrentUserResponses[keyof UsersCurrentUserResponses];

export type UsersPatchCurrentUserData = {
  body: UserUpdate;
  path?: never;
  query?: never;
  url: "/api/v1/users/me";
};

export type UsersPatchCurrentUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersPatchCurrentUserError =
  UsersPatchCurrentUserErrors[keyof UsersPatchCurrentUserErrors];

export type UsersPatchCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersPatchCurrentUserResponse =
  UsersPatchCurrentUserResponses[keyof UsersPatchCurrentUserResponses];

export type UsersDeleteUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/users/{id}";
};

export type UsersDeleteUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersDeleteUserError =
  UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type UsersDeleteUserResponse =
  UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/users/{id}";
};

export type UsersUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersUserError = UsersUserErrors[keyof UsersUserErrors];

export type UsersUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersUserResponse = UsersUserResponses[keyof UsersUserResponses];

export type UsersPatchUserData = {
  body: UserUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/users/{id}";
};

export type UsersPatchUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersPatchUserError =
  UsersPatchUserErrors[keyof UsersPatchUserErrors];

export type UsersPatchUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersPatchUserResponse =
  UsersPatchUserResponses[keyof UsersPatchUserResponses];

export type ClientesDeleteMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/users/me/cliente";
};

export type ClientesDeleteMeResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type ClientesDeleteMeResponse =
  ClientesDeleteMeResponses[keyof ClientesDeleteMeResponses];

export type ClientesReadMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/users/me/cliente";
};

export type ClientesReadMeResponses = {
  /**
   * Successful Response
   */
  200: ClienteRead;
};

export type ClientesReadMeResponse =
  ClientesReadMeResponses[keyof ClientesReadMeResponses];

export type ClientesUpdateMeData = {
  body: ClienteUpdate;
  path?: never;
  query?: never;
  url: "/api/v1/users/me/cliente";
};

export type ClientesUpdateMeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ClientesUpdateMeError =
  ClientesUpdateMeErrors[keyof ClientesUpdateMeErrors];

export type ClientesUpdateMeResponses = {
  /**
   * Successful Response
   */
  200: ClienteRead;
};

export type ClientesUpdateMeResponse =
  ClientesUpdateMeResponses[keyof ClientesUpdateMeResponses];

export type ClientesDeleteData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/users/{id}/cliente";
};

export type ClientesDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ClientesDeleteError =
  ClientesDeleteErrors[keyof ClientesDeleteErrors];

export type ClientesDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type ClientesDeleteResponse =
  ClientesDeleteResponses[keyof ClientesDeleteResponses];

export type ClientesReadData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/users/{id}/cliente";
};

export type ClientesReadErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ClientesReadError = ClientesReadErrors[keyof ClientesReadErrors];

export type ClientesReadResponses = {
  /**
   * Successful Response
   */
  200: ClienteRead;
};

export type ClientesReadResponse =
  ClientesReadResponses[keyof ClientesReadResponses];

export type ClientesUpdateData = {
  body: ClienteAdminUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/users/{id}/cliente";
};

export type ClientesUpdateErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ClientesUpdateError =
  ClientesUpdateErrors[keyof ClientesUpdateErrors];

export type ClientesUpdateResponses = {
  /**
   * Successful Response
   */
  200: ClienteRead;
};

export type ClientesUpdateResponse =
  ClientesUpdateResponses[keyof ClientesUpdateResponses];

export type ProfesionalesDeleteMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/users/me/profesional";
};

export type ProfesionalesDeleteMeResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type ProfesionalesDeleteMeResponse =
  ProfesionalesDeleteMeResponses[keyof ProfesionalesDeleteMeResponses];

export type ProfesionalesReadMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/users/me/profesional";
};

export type ProfesionalesReadMeResponses = {
  /**
   * Successful Response
   */
  200: ProfesionalRead;
};

export type ProfesionalesReadMeResponse =
  ProfesionalesReadMeResponses[keyof ProfesionalesReadMeResponses];

export type ProfesionalesUpdateMeData = {
  body: ProfesionalUpdate;
  path?: never;
  query?: never;
  url: "/api/v1/users/me/profesional";
};

export type ProfesionalesUpdateMeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProfesionalesUpdateMeError =
  ProfesionalesUpdateMeErrors[keyof ProfesionalesUpdateMeErrors];

export type ProfesionalesUpdateMeResponses = {
  /**
   * Successful Response
   */
  200: ProfesionalRead;
};

export type ProfesionalesUpdateMeResponse =
  ProfesionalesUpdateMeResponses[keyof ProfesionalesUpdateMeResponses];

export type ProfesionalesDeleteData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/users/{id}/profesional";
};

export type ProfesionalesDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProfesionalesDeleteError =
  ProfesionalesDeleteErrors[keyof ProfesionalesDeleteErrors];

export type ProfesionalesDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type ProfesionalesDeleteResponse =
  ProfesionalesDeleteResponses[keyof ProfesionalesDeleteResponses];

export type ProfesionalesReadData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/users/{id}/profesional";
};

export type ProfesionalesReadErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProfesionalesReadError =
  ProfesionalesReadErrors[keyof ProfesionalesReadErrors];

export type ProfesionalesReadResponses = {
  /**
   * Successful Response
   */
  200: ProfesionalRead;
};

export type ProfesionalesReadResponse =
  ProfesionalesReadResponses[keyof ProfesionalesReadResponses];

export type ProfesionalesUpdateData = {
  body: ProfesionalAdminUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/users/{id}/profesional";
};

export type ProfesionalesUpdateErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProfesionalesUpdateError =
  ProfesionalesUpdateErrors[keyof ProfesionalesUpdateErrors];

export type ProfesionalesUpdateResponses = {
  /**
   * Successful Response
   */
  200: ProfesionalRead;
};

export type ProfesionalesUpdateResponse =
  ProfesionalesUpdateResponses[keyof ProfesionalesUpdateResponses];

export type ReadItemData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     * Page number
     */
    page?: number;
    /**
     * Size
     * Page size
     */
    size?: number;
  };
  url: "/api/v1/items/";
};

export type ReadItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadItemError = ReadItemErrors[keyof ReadItemErrors];

export type ReadItemResponses = {
  /**
   * Successful Response
   */
  200: PageItemRead;
};

export type ReadItemResponse = ReadItemResponses[keyof ReadItemResponses];

export type CreateItemData = {
  body: ItemCreate;
  path?: never;
  query?: never;
  url: "/api/v1/items/";
};

export type CreateItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateItemError = CreateItemErrors[keyof CreateItemErrors];

export type CreateItemResponses = {
  /**
   * Successful Response
   */
  200: ItemRead;
};

export type CreateItemResponse = CreateItemResponses[keyof CreateItemResponses];

export type DeleteItemData = {
  body?: never;
  path: {
    /**
     * Item Id
     */
    item_id: string;
  };
  query?: never;
  url: "/api/v1/items/{item_id}";
};

export type DeleteItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteItemError = DeleteItemErrors[keyof DeleteItemErrors];

export type DeleteItemResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ClientOptions = {
  baseURL: `${string}://openapi.json` | (string & {});
};
