"""add_email_otps_table

Revision ID: a067ad066d81
Revises: d8c5f7a9b3e1
Create Date: 2026-08-18 12:38:24.521702

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a067ad066d81"
down_revision: Union[str, None] = "d8c5f7a9b3e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_otps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("code_hash", sa.String(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_ip", sa.String(), nullable=True),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_email_otps_email"), "email_otps", ["email"], unique=False)
    # NOTE: autogenerate also proposed dropping ix_refresh_tokens_expires_at
    # and ix_refresh_tokens_user_id here — that's pre-existing drift between
    # models.py and the DB (those indexes aren't declared on the RefreshToken
    # model but exist from an earlier migration), unrelated to this change.
    # Deliberately left alone; dropping them would hurt refresh-token lookup
    # performance for no reason tied to this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_email_otps_email"), table_name="email_otps")
    op.drop_table("email_otps")
    # ### end Alembic commands ###
